basicoDjango/accounts/urls.py
from django.urls import path, include


app_name='contas'
urlpatterns = [

]

basicoDjango/basicoDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls',namespace='coracao')),
    path('cursos/', include('courses.urls',namespace='curso')),
    path('conta/', include('accounts.urls',namespace='contas')),
]

#imagens
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

basicoDjango/core/urls.py
from django.urls import path, re_path
from core.views import home,base,contato

app_name='coracao'
urlpatterns = [
    path('teste/',home),
    re_path(r'^$',base, name='base'),
    re_path(r'^contato/$',contato, name='contact'),
]

basicoDjango/courses/urls.py
from django.urls import path
from courses.views import courses, detalhes


app_name='curso'
urlpatterns = [
    path('', courses, name="curso"),
    #path('<int:pk>/', detalhes, name="detalhes")
    path('<slug:title>/', detalhes, name="detalhes")
]

basicoDjango/accounts/models.py
from django.db import models

# Create your models here.

basicoDjango/courses/models.py
from django.db import models
from django.urls import reverse

class CourseManager(models.Manager):

    def search(self,query):
        return self.get_queryset().filter(models.Q(name__icontains=query) | \
            models.Q(descricao__icontains=query))

# Create your models here.
class Course(models.Model):

    name = models.CharField('Nome',max_length=100)
    slug = models.SlugField('Atalho')
    descricao = models.TextField('Descrição curta',blank=True)
    about = models.TextField('Descrição',blank=True)
    startDate = models.DateField('Data de Inicio',null=True,blank=True)
    imagem = models.ImageField(upload_to='cursos/images',verbose_name='Imagem',null=True,blank=True)
    
    create_at = models.DateTimeField('Criado em ',auto_now_add=True)
    update_at = models.DateTimeField('Ultima atualização ',auto_now=True)

    objects = CourseManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('curso:detalhes' ,args=[self.slug])
    
    

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'
        ordering = ["name"]

basicoDjango/courses/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings

from courses.mail import send_mail_teamplate

class ContactCourse(forms.Form):
    nome = forms.CharField(label='Nome', max_length=50)
    email = forms.EmailField(label="E-Mail")
    mensagem = forms.CharField(label="Mensagem",widget=forms.Textarea,required=False)

    def send_mail(self,course):
        subject = 'Contato sobre o Curso %s' % course
        #mensagem = 'Nome: %(name)s;E-mail: %(email)s;%(mensagem)s'
        contexto = {
            'name':self.cleaned_data['nome'],
            'email':self.cleaned_data['email'],
            'mensagem':self.cleaned_data['mensagem']
        }
        # mensagem = mensagem %contexto
        # send_mail(subject, mensagem, settings.DEFAULT_FROM_EMAIL, [settings.CONTACT_EMAIL])

        send_mail_teamplate(subject, 'email_template.html', contexto, [settings.CONTACT_EMAIL])

basicoDjango/accounts/views.py
from django.shortcuts import render

# Create your views here.

basicoDjango/core/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'home.html',{"usuario":"NETTO"})

def base(request):
    return render(request,'base.html')

def contato(request):
    return render(request,'contact.html')

basicoDjango/courses/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest
from courses.models import Course
from courses.forms import ContactCourse

# Create your views here.
def courses(request):
    contexto={
        'courses':Course.objects.all()
    }
    return render(request,'courses.html', contexto)

# def detalhes(request,pk):
#     course = get_object_or_404(Course,pk=pk)
#     return render(request,'details.html',{"course":course})

def detalhes(request, title):
    course = get_object_or_404(Course,slug=title)

    contexto = {}

    if request.method == 'POST':
        form = ContactCourse(request.POST)
        if form.is_valid():
            
            form.send_mail(course)

            contexto['is_valid']=True
            print(form.cleaned_data) 
            form = ContactCourse()
    else:
        form = ContactCourse()

    contexto['form']=form
    contexto['course']=course

    return render(request,'details.html',contexto)

basicoDjango/core/templates/base.html
{% extends "fonte.html" %}
{% block content %}

    <div class="splash">
        <div class="pure-g-r">
            <div class="pure-u-1">
                <div class="l-box splash-text">
                    <h1 class="splash-head">
                        Uma Simples Plataforma de Ensino a Distância
                    </h1>
                    <h2 class="splash-subhead">
                        O Simple MOOC visa simplificar o ensino a distância, provendo ferramentas objetivas e de fácil uso para cursos a distância.
                    </h2>
                    <p>
                        <a href="#" class="pure-button primary-button">Saiba mais</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Vídeo-aulas e materiais digitais</h4>
                    <h3>Publique suas aulas</h3>
                    <p>
                        O Simple MOOC tem um sistema simples e prático para que o professor disponibilize vídeo-aulas e materiais digitais como: pdf's, slides, imagens ...
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Vídeo aulas e materiais digitais.">
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Fórum de Dúvidas">
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Fórum de Dúvidas</h4>
                    <h3>Interaja com seus Alunos</h3>
                    <p>
                        No Simple MOOC você pode ter seu próprio sistema de fórum para que seus alunos possam interagir com você e com os outros alunos
                    </p>
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Exercícios</h4>
                    <h3>Crie exercícios para avaliar seus alunos</h3>
                    <p>
                        Você pode criar exercícios para que os alunos possam ser avaliados e todo o controle de notas e resolução dos exercícios é controlado pela plataforma, facilitando sua vida
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Exercícios">
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Mural de Avisos">
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Mural de Avisos</h4>
                    <h3>Envie anúncios diretamente para os alunos</h3>
                    <p>
                        Organize os avisos do seu curso de forma fácil e simples.
                    </p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

basicoDjango/core/templates/contact.html
{% extends "fonte.html" %}
{% block content %}

<div class="content">
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <h1>Fale conosco</h1>
            <p>Você pode entrar em contato conosco tanto por e-mail como pelas redes sociais, abaixo seguem os links para contato:</p>
            <h4>Links</h4>
            <ul>
                <li>E-mail: <a href="mailto:contato@simplemooc.org">contato@simplemooc.org</a></li>
                <li>Twitter: <a href="https://twitter.com/simplemooc">@simplemooc</a></li>
            </ul>
        </div>
    </div>
    
{% endblock %}

basicoDjango/core/templates/fonte.html
<!doctype html>
{% load static%}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple MOOC - Uma simples plataforma de ensino a distância" />
    <title>Simple MOOC</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
</head>
<body>
    <div class="header">
        <div class="pure-menu pure-menu-open pure-menu-fixed pure-menu-horizontal">
            <a class="pure-menu-heading" href="{% url 'coracao:base' %}"">SIMPLE MOOC</a>
            <ul>
                <li class="pure-menu-selected"><a href="{% url 'coracao:base' %}">Início</a></li>
                <li><a href="{% url 'curso:curso' %}">Cursos</a></li>
                <li><a href="{% url 'coracao:contact' %}">Contato</a></li>
                <li><a href="#">Login</a></li>
            </ul>
        </div> 7
    </div>
    {% block content %}{% endblock %}
<div class="content">
    <div class="footer">
        Simple MOOC - Uma simples plataforma de ensino a distância
    </div>
</div>
<script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
</body>
</html>

basicoDjango/core/templates/home.html
OLÁ MUNDO E {{usuario}}.

basicoDjango/courses/templates/courses.html
{% extends "fonte.html" %}

{% load static %}

{% block content %}
<br>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <h4 class="content-subhead">Listagem de Cursos do SimpleMOOC</h4>
            <p>Abaixo a lista de cursos disponíveis na plataforma</p>
        </div>
    </div>
</div>

{% for course in courses %}

<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <a href={% url 'curso:detalhes' course.slug %}>
            {% if course.imagem %}
            <img src="{{ course.imagem.url }}" alt="{{ course.name }}" />
            {% else %}
            <img src={% static 'img/name.jpg' %} alt="{{ course.name }}" />
            {% endif %}
            </a>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead"><a href="{{course.get_absolute_url}}" title="">{{ course.name}}</a></h4>
        </div>
            {{course.descricao | linebreaks}}
    </div>
</div>

{% empty %}

<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <p>Nenhum curso está disponível na plataforma</p>
        </div>
    </div>
</div>

{% endfor %}

{% endblock %}

basicoDjango/courses/templates/details.html
{% extends "fonte.html" %}

{% load static %}

{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    {{ course.name }}
                </h1>
                <h2 class="splash-subhead">
                    {{ course.descricao }}
                </h2>
                <p>
                    <a href="#" class="pure-button primary-button">Inscreva-se</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Sobre o Curso</h4>
            {{ course.about|linebreaks }}
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            {% if course.imagem %}
            <img src="{{ course.imagem.url }}" alt="{{ course.name }}" />
            {% else %}
            <img src="{% static 'img/name.jpg' %}" alt="{{ course.name }}" />
            {% endif %}
            <h4>Dúvidas?</h4>
            <p>
                <a href="#contato" title="" class="pure-button">Fale Conosco</a>
            </p>
        </div>
    </div>
</div>

<div class="pure-g-r content-ribbon" id="contato">
        <div class="pure-u-1">
            <h3>Tire sua dúvida sobre o Curso</h3>
            {% if is_valid %}
                <p>ENVIADO COM SUCESSO!!</P>
            {% endif %}
            <form class="pure-form pure-form-aligned", method="post">
                {% csrf_token %}
                <fieldset>
                    <table>
                        <tbody>
                            <tr>
                                {{ form.as_table }}
                            </tr>
                        </tbody>
                    </table>
                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>

{% endblock %}

basicoDjango/courses/templates/email_template.html
{% load static %}
<p><strong>Nome: </strong>{{nome}}</p>
<p><strong>E-mail: </strong>{{email}}</p>
<br>
<p><strong>Mensagem: </strong></p>
<p>{{mensagem|linebreaks}}</p>